"""Schema 模块"""
from .common import (
    ApiResponse,
    PaginatedParams,
    PaginatedResponse,
    ValidationError,
    ErrorResponse,
    success_response,
    error_response,
)

from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserSettingsBase,
    UserSettingsUpdate,
    UserSettingsResponse,
    AIConfigBase,
    AIConfigCreate,
    AIConfigUpdate,
    AIConfigResponse,
    PinSetupRequest,
    PinVerifyRequest,
    PinChangeRequest,
    PinVerifyResponse,
    PinSetupResponse,
    AuthStatusResponse,
    LockResponse,
)

from .system import (
    SystemType,
    SystemBase,
    SystemCreate,
    SystemUpdate,
    SystemResponse,
    SystemScoreUpdate,
    SystemScoreUpdateResponse,
    SystemLogBase,
    SystemLogCreate,
    SystemLogResponse,
    SystemActionBase,
    SystemActionCreate,
    SystemActionUpdate,
    SystemActionResponse,
    SystemActionDeleteResponse,
    SystemListParams,
    SystemLogListParams,
)

from .journal import (
    MoodType,
    DiaryBase,
    DiaryCreate,
    DiaryUpdate,
    DiaryResponse,
    DiaryDeleteResponse,
    DiaryListParams,
    DiaryAttachmentBase,
    DiaryAttachmentResponse,
    DiaryEditHistoryResponse,
)

from .insight import (
    AIProvider,
    InsightBase,
    InsightCreate,
    InsightResponse,
    InsightGenerateRequest,
    InsightGenerateResponse,
    InsightListParams,
    InsightItem,
)

__all__ = [
    # Common
    "ApiResponse",
    "PaginatedParams",
    "PaginatedResponse",
    "ValidationError",
    "ErrorResponse",
    "success_response",
    "error_response",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserSettingsBase",
    "UserSettingsUpdate",
    "UserSettingsResponse",
    "AIConfigBase",
    "AIConfigCreate",
    "AIConfigUpdate",
    "AIConfigResponse",
    "PinSetupRequest",
    "PinVerifyRequest",
    "PinChangeRequest",
    "PinVerifyResponse",
    "PinSetupResponse",
    "AuthStatusResponse",
    "LockResponse",
    # System
    "SystemType",
    "SystemBase",
    "SystemCreate",
    "SystemUpdate",
    "SystemResponse",
    "SystemScoreUpdate",
    "SystemScoreUpdateResponse",
    "SystemLogBase",
    "SystemLogCreate",
    "SystemLogResponse",
    "SystemActionBase",
    "SystemActionCreate",
    "SystemActionUpdate",
    "SystemActionResponse",
    "SystemActionDeleteResponse",
    "SystemListParams",
    "SystemLogListParams",
    # Journal
    "MoodType",
    "DiaryBase",
    "DiaryCreate",
    "DiaryUpdate",
    "DiaryResponse",
    "DiaryDeleteResponse",
    "DiaryListParams",
    "DiaryAttachmentBase",
    "DiaryAttachmentResponse",
    "DiaryEditHistoryResponse",
    # Insight
    "AIProvider",
    "InsightBase",
    "InsightCreate",
    "InsightResponse",
    "InsightGenerateRequest",
    "InsightGenerateResponse",
    "InsightListParams",
    "InsightItem",
]
